spring:
  datasource:
    username: root
    password: h123
    url: jdbc:mysql://localhost:3306/jd?serverTimezone=GMT&amp;useUnicode=true&amp;characterEncoding=UTF8
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  type-aliases-package: org.lanqiao.jdlogin.demo.entity,java.lang
#  type-aliases-package: java.lang
  mapper-locations: classpath:org/lanqiao/jdlogin/demo/mapper/*.xml

#showSql
logging:
  level:
    org.lanqiao.jdlogin.demo:
        mapper : debug
